name: Trivy
description: Trivy FS Scan
author: Hari
requirements:
  - bash
  - docker
configuration:
  properties:
    exit-code:
      type: integer
    severity:
      type: string
    ignore-unfixed:
      type: boolean
    image:      
      type: string
  additionalProperties: false
